spring:
  application:
    name: Travel Management System
  datasource:
    url: jdbc:postgresql://localhost:5432/travel?currentSchema=travel
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090